Fix _.includes error - change to _.contains for underscore v1.4.3
- Line 829: Changed _.includes() to _.contains()
- Underscore.js v1.4.3 (2013) doesn't support _.includes
- _.includes was added in v1.8.0 (2015)
- Fixes 'TypeError: _.includes is not a function' when loading playlists